"""
Git Operations Service - FIXED VERSION
Enhanced error handling and conflict detection
"""

import os
from typing import Dict, Any
from git import Repo
import requests


def create_pull_request(
    github_token: str,
    repo_name: str,
    pr_title: str,
    pr_body: str = None
) -> Dict[str, Any]:
    """
    Create PR from fork dev -> upstream dev

    Args:
        github_token: GitHub personal access token
        repo_name: Repository name in format "org/repo"
        pr_title: Title for the pull request
        pr_body: Optional PR description

    Returns:
        Dictionary with PR details including 'html_url', 'number', etc.

    Raises:
        RuntimeError: If PR creation fails with detailed error message
    """

    fork_owner = os.getenv("GITHUB_USERNAME")
    if not fork_owner:
        raise RuntimeError(
            "❌ GITHUB_USERNAME not set in environment.\n"
            "Please add your GitHub username to .env file:\n"
            "GITHUB_USERNAME=your_username"
        )

    url = f"https://api.github.com/repos/{repo_name}/pulls"

    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    if pr_body is None:
        pr_body = (
            "## 🤖 Automated Data Platform Intake\n\n"
            "This PR was generated automatically by the MIW Data Platform Intake Bot.\n\n"
            "**Source:** `{fork_owner}:dev` branch\n"
            "**Target:** `{repo_name}:dev` branch\n\n"
            "---\n"
            "*Generated by MIW Data Platform Assistant*"
        ).format(fork_owner=fork_owner, repo_name=repo_name)

    # The head should be in format: "username:branch"
    payload = {
        "title": pr_title,
        "head": f"{fork_owner}:dev",
        "base": "dev",
        "body": pr_body,
    }

    try:
        print(f"\n🔄 Creating PR: {pr_title}")
        print(f"   From: {fork_owner}:dev → To: {repo_name}:dev")

        response = requests.post(url, headers=headers, json=payload, timeout=30)

        # SUCCESS - PR created
        if response.status_code == 201:
            pr_data = response.json()
            print(f"✅ PR created successfully!")
            print(f"   URL: {pr_data['html_url']}")
            print(f"   Number: #{pr_data['number']}")
            return pr_data

        # Handle specific error cases
        error_data = response.json()

        # 422 - Validation error (usually duplicate PR)
        if response.status_code == 422:
            error_message = str(error_data.get('errors', error_data)).lower()

            # Check if it's a duplicate PR error
            if "pull request already exists" in error_message or "already exists" in error_message:
                # Try to get the existing PR details
                existing_pr = get_existing_pr(github_token, repo_name, fork_owner)

                if existing_pr:
                    raise RuntimeError(
                        f"⚠️ A pull request already exists!\n\n"
                        f"**Existing PR:** {existing_pr['title']}\n"
                        f"**URL:** {existing_pr['html_url']}\n"
                        f"**Number:** #{existing_pr['number']}\n\n"
                        f"Your new commits have been pushed to `{fork_owner}:dev` "
                        f"and will automatically appear in the existing PR.\n\n"
                        f"**Options:**\n"
                        f"1. Keep the existing PR (your changes are already there)\n"
                        f"2. Close the existing PR on GitHub and create a new one"
                    )
                else:
                    raise RuntimeError(
                        f"⚠️ A pull request already exists from {fork_owner}:dev to {repo_name}:dev.\n\n"
                        f"Your changes have been pushed to your fork's dev branch.\n"
                        f"Check your open PRs on GitHub to see the existing PR."
                    )

            # Check if it's a "no commits" error
            elif "no commits" in error_message:
                raise RuntimeError(
                    f"❌ No commits to create PR.\n\n"
                    f"The branches `{fork_owner}:dev` and `{repo_name}:dev` are already in sync.\n"
                    f"Make some changes first before creating a PR."
                )

            else:
                raise RuntimeError(
                    f"❌ GitHub validation error:\n{error_data.get('message', 'Unknown error')}\n\n"
                    f"Details: {error_data}"
                )

        # 401 - Authentication error
        elif response.status_code == 401:
            raise RuntimeError(
                f"❌ Authentication failed!\n\n"
                f"Your GITHUB_TOKEN is invalid or expired.\n"
                f"Please update GITHUB_TOKEN in your .env file with a valid token.\n\n"
                f"Create a new token at: https://github.com/settings/tokens"
            )

        # 404 - Repository not found
        elif response.status_code == 404:
            raise RuntimeError(
                f"❌ Repository not found!\n\n"
                f"Repository '{repo_name}' doesn't exist or you don't have access.\n\n"
                f"Please verify:\n"
                f"1. REPO_NAME in .env is correct (format: 'org/repo')\n"
                f"2. You have access to this repository\n"
                f"3. Your GitHub token has the right permissions"
            )

        # 403 - Forbidden
        elif response.status_code == 403:
            raise RuntimeError(
                f"❌ Permission denied!\n\n"
                f"Your GitHub token doesn't have permission to create PRs in '{repo_name}'.\n\n"
                f"Make sure your token has 'repo' scope enabled."
            )

        # Other errors
        else:
            raise RuntimeError(
                f"❌ GitHub API error (status {response.status_code}):\n"
                f"{response.text}\n\n"
                f"Please check your GitHub settings and try again."
            )

    except requests.exceptions.Timeout:
        raise RuntimeError(
            "❌ Request timed out!\n\n"
            "GitHub API is taking too long to respond.\n"
            "Please check your internet connection and try again."
        )

    except requests.exceptions.ConnectionError:
        raise RuntimeError(
            "❌ Connection failed!\n\n"
            "Cannot connect to GitHub API.\n"
            "Please check your internet connection."
        )

    except requests.exceptions.RequestException as e:
        raise RuntimeError(f"❌ Network error: {str(e)}")


def get_existing_pr(github_token: str, repo_name: str, fork_owner: str) -> Dict[str, Any]:
    """
    Get details of existing PR from fork to upstream

    Args:
        github_token: GitHub personal access token
        repo_name: Repository name in format "org/repo"
        fork_owner: GitHub username of fork owner

    Returns:
        Dictionary with PR details or None if no PR exists
    """
    try:
        url = f"https://api.github.com/repos/{repo_name}/pulls"
        headers = {
            "Authorization": f"Bearer {github_token}",
            "Accept": "application/vnd.github+json",
        }

        params = {
            "state": "open",
            "head": f"{fork_owner}:dev",
            "base": "dev"
        }

        response = requests.get(url, headers=headers, params=params, timeout=10)

        if response.status_code == 200:
            prs = response.json()
            if prs and len(prs) > 0:
                return {
                    "html_url": prs[0]["html_url"],
                    "title": prs[0]["title"],
                    "number": prs[0]["number"],
                    "state": prs[0]["state"]
                }

        return None

    except Exception as e:
        print(f"Warning: Could not fetch existing PR details: {e}")
        return None


def check_existing_pr(github_token: str, repo_name: str, fork_owner: str) -> Dict[str, Any]:
    """
    Check if there's an existing open PR from fork dev to upstream dev

    Args:
        github_token: GitHub personal access token
        repo_name: Repository name in format "org/repo"
        fork_owner: GitHub username of fork owner

    Returns:
        Dictionary with:
        - 'exists': bool
        - 'url': str (if exists)
        - 'title': str (if exists)
        - 'number': int (if exists)
    """
    try:
        existing = get_existing_pr(github_token, repo_name, fork_owner)

        if existing:
            return {
                "exists": True,
                "url": existing["html_url"],
                "title": existing["title"],
                "number": existing["number"]
            }

        return {"exists": False}

    except Exception as e:
        print(f"Error checking existing PR: {e}")
        return {"exists": False}


def validate_git_config() -> Dict[str, Any]:
    """
    Validate that all required Git/GitHub configuration is present

    Returns:
        Dictionary with validation results
    """
    issues = []

    # Check GITHUB_TOKEN
    if not os.getenv("GITHUB_TOKEN1"):
        issues.append("GITHUB_TOKEN1 not set in .env file")

    # Check GITHUB_USERNAME
    if not os.getenv("GITHUB_USERNAME"):
        issues.append("GITHUB_USERNAME not set in .env file")

    # Check REPO_NAME
    repo_name = os.getenv("REPO_NAME")
    if not repo_name:
        issues.append("REPO_NAME not set in .env file")
    elif "/" not in repo_name:
        issues.append("REPO_NAME must be in format 'org/repo'")

    return {
        "valid": len(issues) == 0,
        "issues": issues
    }